### ISSUE TITLE
install not work

### ISSUE THREAD

**Issue by schossler** [fasaro/magento2-es_uy-language-pack#2]
composer require fasaro/magento2-es_uy-language-pack dev-master
php bin/magento setup:static-content:deploy es_UY

return 
es_UY argument has invalid value, please run info:language:list for list of available locales

I test this in magento 2.4.6 with PHP 8.1 !

**Comment by fasaro** [comment]
Hello
unfortunately magento has reduced the list of languages in Spanish, including Uruguay (es_UY) I suggest you add one that is available

`| Spanish (Argentina)                            | es_AR      |
| Spanish (Bolivia)                              | es_BO      |
| Spanish (Chile)                                | es_CL      |
| Spanish (Colombia)                             | es_CO      |
| Spanish (Costa Rica)                           | es_CR      |
| Spanish (Mexico)                               | es_MX      |
| Spanish (Panama)                               | es_PA      |
| Spanish (Peru)                                 | es_PE      |
| Spanish (Spain)                                | es_ES      |
| Spanish (United States)                        | es_US      |
| Spanish (Venezuela)                            | es_VE      |`

**Comment by fasaro** [comment]
Hello
unfortunately magento has reduced the list of languages in Spanish, including Uruguay (es_UY) I suggest you add one that is available

> | Spanish (Argentina)                            | es_AR      |
| Spanish (Bolivia)                              | es_BO      |
| Spanish (Chile)                                | es_CL      |
| Spanish (Colombia)                             | es_CO      |
| Spanish (Costa Rica)                           | es_CR      |
| Spanish (Mexico)                               | es_MX      |
| Spanish (Panama)                               | es_PA      |
| Spanish (Peru)                                 | es_PE      |
| Spanish (Spain)                                | es_ES      |
| Spanish (United States)                        | es_US      |
| Spanish (Venezuela)                            | es_VE      |
